name = "PostCFD"
uuid = "7569ea13-7d3d-4d5a-b07b-f32353060e2b"
authors = ["Yuta Iwatani <yuta.iwatani.cfd@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
